services:

  database:
    image: 'mariadb:12.0'
    container_name: database
    restart: always
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql